version: '3.5'


services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: maximyasn
      POSTGRES_PASSWORD: maxim1100
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "2345:5432"


volumes:
  postgres-db:
    driver: local